### ISSUE TITLE
Request to contribute

### ISSUE THREAD

**Issue by ghost** [crearth/c#1]
Hey , I would like to contribute to your repo , can you let me know where I should store the files and if there's a list of programs that you would like to finish first

Cheers

**Comment by crearth** [comment]
Hi,

Thanks for your suggestion to contribute to my repo. At the moment I have no further plans with this repo, but if you want to contribute, you can upload some cpp files in a folder called "examples". It can be whatever you want, I don't have a list of programs I want finished first.

Cheers

**Comment by ghost** [comment]
Hey , 

Sure will do that , Have a good day
